server:
  port: 2001
spring:
  application:
    name: seata-order-services
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
        # 需要与seata-server配置的相对应
    nacos:
      discovery:
        server-addr: 192.168.1.20:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.20:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml